name: Github Actions Test
run-name: ${{ github.actor }} is testing out GitHub Actions.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a script
        run: echo "Hello, Github Actions! From repository ${{ github.actor }}:${{ github.repository}}"
